wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1646770772
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
episodes:
  desc: null
  value: 1000000
eps_decay:
  desc: null
  value: 50000
eps_end:
  desc: null
  value: 0.1
eps_start:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
log_interval:
  desc: null
  value: 25
lr:
  desc: null
  value: 0.001
num_steps:
  desc: null
  value: 1000
replay_size:
  desc: null
  value: 2000
target_update:
  desc: null
  value: 5000
